name: Build and Lint Flatpak Application

on: 
  workflow_dispatch:  # 允许手动触发此workflow

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/cache@v3
      with:
        path: .flatpak-builder
        key: ${{ runner.os }}-flatpak-builder

    - name: Install flatpak and flatpak-builder
      run: |
        sudo add-apt-repository ppa:flatpak/stable
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder

    - name: Add Flathub remote
      run: sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install the lint tool
      run: sudo flatpak install flathub -y org.flatpak.Builder
    
    - name: Install SDKs
      run: |
        sudo flatpak install flathub org.freedesktop.Sdk//23.08 -y
        sudo flatpak install flathub org.freedesktop.Sdk.Extension.dotnet6//23.08 -y

    - name: Build the application
      run: flatpak-builder --force-clean --repo=repo --install-deps-from=flathub builddir net.opentabletdriver.OpenTabletDriver.yaml

    - name: Run lint
      run: |
        sudo flatpak run --command=flatpak-builder-lint org.flatpak.Builder//stable --exceptions manifest net.opentabletdriver.OpenTabletDriver.yaml
      continue-on-error: true

    - name: Create Flatpak bundle
      if: ${{ success() }}
      run: flatpak build-bundle repo myapp.flatpak net.opentabletdriver.OpenTabletDriver

    - name: Upload Flatpak bundle as an artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: myapp-flatpak
        path: myapp.flatpak
