name: Flatpak Build and Lint

on:
  workflow_dispatch:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Flatpak and Flatpak-Builder
      run: |
        sudo add-apt-repository ppa:flatpak/stable -y
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder

    - name: Set up Flathub remote
      run: |
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install SDKs
      run: |
        flatpak install flathub org.freedesktop.Sdk//23.08 -y
        flatpak install flathub org.freedesktop.Sdk.Extension.dotnet6//23.08 -y

    - name: Install lint tool
      run: |
        flatpak install flathub -y org.flatpak.Builder

    - name: Build Flatpak app
      run: |
        flatpak-builder --force-clean --repo=repo --state-dir=flatpak-builder-state build-dir net.opentabletdriver.OpenTabletDriver.yaml
        flatpak build-bundle repo net.opentabletdriver.OpenTabletDriver.flatpak net.opentabletdriver.OpenTabletDriver

    - name: Lint manifest
      run: |
        flatpak run --command=flatpak-builder-lint org.flatpak.Builder//stable --exceptions manifest net.opentabletdriver.OpenTabletDriver.yaml
      continue-on-error: true

    - name: Lint appstream
      run: |
        flatpak run --command=flatpak-builder-lint org.flatpak.Builder//stable --exceptions appstream build-dir/files/share/appinfo/net.opentabletdriver.OpenTabletDriver.appdata.xml
      continue-on-error: true

    - name: Upload Flatpak as Artifact if lint passes
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: flatpak-artifact
        path: net.opentabletdriver.OpenTabletDriver.flatpak
