name: Flatpak Build and Lint

on:
  workflow_dispatch:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache flatpak-builder builds
      uses: actions/cache@v3
      with:
        path: .flatpak-builder
        key: ${{ runner.os }}-flatpak-builder-${{ hashFiles('net.opentabletdriver.OpenTabletDriver.yaml') }}

    - name: Install flatpak and flatpak-builder
      run: |
        sudo add-apt-repository ppa:flatpak/stable -y
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder

    - name: Set up flathub remote
      run: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install dependencies
      run: |
        flatpak install flathub org.freedesktop.Sdk//23.08 org.freedesktop.Platform//23.08 -y --user
        flatpak install flathub org.flatpak.Builder -y --user

    - name: Build the flatpak application
      run: flatpak-builder --user --force-clean --install-deps-from=flathub --repo=repo builddir net.opentabletdriver.OpenTabletDriver.yaml

    - name: Install lint tool
      run: flatpak install flathub -y --user org.flatpak.Builder

    - name: Run lint check
      run: flatpak run --command=flatpak-builder-lint org.flatpak.Builder//localtest --exceptions manifest net.opentabletdriver.OpenTabletDriver.yaml

    - name: Upload artifact if lint passes
      uses: actions/upload-artifact@v3
      with:
        name: flatpak-artifact
        path: repo/*.flatpak
        if-no-files-found: error
