name: Update OpenTabletDriver

on:
  workflow_dispatch:

jobs:
  update-opentabletdriver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Flatpak and Flatpak-Builder
        run: |
          sudo add-apt-repository ppa:flatpak/stable -y
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
  
      - name: Set up Flathub remote
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Install SDKs and Runtime
        run: |
          flatpak install flathub org.freedesktop.Platform//23.08 -y
          flatpak install flathub org.freedesktop.Sdk//23.08 -y
          flatpak install flathub org.freedesktop.Sdk.Extension.dotnet6//23.08 -y
        
      - name: Download OpenTabletDriver latest release
        run: |
          wget $(curl -s https://api.github.com/repos/OpenTabletDriver/OpenTabletDriver/releases/latest | grep 'browser_download_url' | cut -d '"' -f 4)
      
      - name: Generate linux-x64 and linux-arm64 JSON
        run: |
          wget https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/master/dotnet/flatpak-dotnet-generator.py
          chmod +x flatpak-dotnet-generator.py
          ./flatpak-dotnet-generator.py linux-x64.json ./OpenTabletDriver.UX.Gtk/OpenTabletDriver.UX.Gtk.csproj --runtime linux-x64 --freedesktop 23.08
          ./flatpak-dotnet-generator.py linux-arm64.json ./OpenTabletDriver.UX.Gtk/OpenTabletDriver.UX.Gtk.csproj --runtime linux-arm64 --freedesktop 23.08
      
      - name: Replace JSON files in current project
        run: |
          mv linux-x64.json ./sources/linux-x64.json
          mv linux-arm64.json ./sources/linux-arm64.json
      
      - name: Update net.opentabletdriver.OpenTabletDriver.yaml
        run: |
          TAG_NAME=$(curl -s https://api.github.com/repos/OpenTabletDriver/OpenTabletDriver/releases/latest | grep 'tag_name' | cut -d '"' -f 4)
          sed -i "s/tag: .*/tag: ${TAG_NAME}/" net.opentabletdriver.OpenTabletDriver.yaml
          echo -e "\n# Generated by GitHub Actions. $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> net.opentabletdriver.OpenTabletDriver.yaml
      
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Update OpenTabletDriver to latest release"
          pr_body: "Automatically update OpenTabletDriver references to the latest release."
          pr_label: "automated-pr"
          commit_message: "feat: update OpenTabletDriver to latest release"
